version: '3.8'

services:
  taipy-app:
    build:
      context: .
      dockerfile: taipy-app.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app       # Monta o volume local para desenvolvimento
    # environment:
    #   - STREAMLIT_SERVER_HEADLESS=true
    #   - STREAMLIT_SERVER_PORT=8501
    command: ["tail", "-f", "/dev/null"]  # Mantém o container ativo
